# Clave de release PÚBLICA (app personal). Ver README: "Actualizar sin perder la configuración".
storeFile=keystore/pixelcarplayer-release.jks
storePassword=SrSH1S8mj82vfSjzdp95
keyPassword=SrSH1S8mj82vfSjzdp95
keyAlias=pixelcarplayer
